In [1]:
from google.cloud import bigquery
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
from itertools import islice
warnings.filterwarnings('ignore')

sns.set_theme(style="whitegrid")

pd.set_option("display.max_columns", 100)
pd.set_option("display.float_format", "{:,.2f}".format)

# Helper Functions

In [2]:
%load_ext autoreload
%autoreload 2

import sys
from pathlib import Path

SRC_DIR = Path.cwd().parent
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from eda_helpers import (
    DEFAULT_PERCENTILES,
    build_distribution_summary,
    build_outlier_summary,
    build_segment_summary,
    cast_numeric_fields,
    plot_bucket_counts,
    plot_correlation_heatmap,
    plot_full_and_clipped_boxplot,
    plot_histogram_with_log,
    plot_scatter_pairs,
    plot_slices_of_segments_boxplot,
)

CHART_DIR = Path("charts")

# Statistic summary - Priced in April

In [3]:
PROJECT_ID = "gannett-datascience"
TABLE_ID = "gannett-datascience.test_results_zone.ss_test_result_v3-2"

NUMERIC_FIELDS = [
    "frequency",
    "breadth",
    "tenure",
    "tt_cost"
]
SEGMENT_FIELDS = [
    "src_risk_tier",
    "cohort",
    "Treatment",
    "contact_channel",
    "status",
    "contact_timing",
    "repeatedly_called"
]
IDS = [
    "billing_account",
    "id_subscrip",
    "email_date"
]

client = bigquery.Client(project=PROJECT_ID)

In [4]:
query = f"""
SELECT
  {", ".join(NUMERIC_FIELDS + SEGMENT_FIELDS + IDS)}
FROM `{TABLE_ID}`
where email_date < '2026-05-01'
"""
df = client.query(query).to_dataframe()
df = cast_numeric_fields(df, NUMERIC_FIELDS)
df['contact_channels'] = df['contact_channel'].replace({'Online first': 'Contacted both ways', 'Called-In first': 'Contacted both ways'})
df['src_risk_tier'] = df['src_risk_tier']+' risk'
df_action = df[df["status"].ne("No Action yet")].copy()
df_no_action = df[df["status"].eq("No Action yet")].copy()
df_save = df[df["status"].eq("saved")].copy()
df_stop = df[df["status"].eq("stoped")].copy()

In [5]:
print("Shapes: total ", df.shape, "action ", df_action.shape, "no action ", df_no_action.shape, "save ", df_save.shape, "stop ", df_stop.shape)
# df_action.info()

Shapes: total  (9398, 15) action  (1531, 15) no action  (7867, 15) save  (589, 15) stop  (942, 15)

In [6]:
# df_action.describe(include="all").T

In [7]:
percentiles = DEFAULT_PERCENTILES
dfs = {"No Action": df_no_action, "Action": df_action, "Saved": df_save, "Stopped": df_stop}

for name, df_i in dfs.items():
    print(f"Distribution Summary for {name} users:")
    distribution_summary = build_distribution_summary(df_i, NUMERIC_FIELDS, percentiles)
    display(distribution_summary)

Distribution Summary for No Action users:

,field,row_count,null_count,null_pct,zero_count,negative_count,min,max,mean,median,std,p01,p05,p10,p25,p50,p75,p90,p95,p99
0,frequency,7867,6,0.08,1632,0,0.00,91.00,38.46,29.00,35.37,0.00,0.00,0.00,2.00,29.00,77.00,90.00,91.00,91.00
1,breadth,7867,6,0.08,2466,0,0.00,21.00,4.18,3.00,4.24,0.00,0.00,0.00,0.00,3.00,7.00,10.00,12.00,16.00
2,tenure,7867,6,0.08,0,0,208.00,"27,867.00","1,382.95","1,354.00",886.36,324.00,337.00,504.00,997.00,"1,354.00","1,635.00","2,069.00","2,460.00","3,405.80"
3,tt_cost,7867,6,0.08,32,0,0.00,"9,279.71",571.25,502.83,439.16,107.89,112.89,166.27,374.25,502.83,704.96,949.38,"1,279.15","1,764.45"

Distribution Summary for Action users:

,field,row_count,null_count,null_pct,zero_count,negative_count,min,max,mean,median,std,p01,p05,p10,p25,p50,p75,p90,p95,p99
0,frequency,1531,3,0.20,183,0,0.00,91.00,45.90,46.00,34.53,0.00,0.00,0.00,9.00,46.00,82.00,90.00,91.00,91.00
1,breadth,1531,3,0.20,292,0,0.00,20.00,5.04,4.00,4.19,0.00,0.00,0.00,1.00,4.00,8.00,11.00,13.00,15.73
2,tenure,1531,3,0.20,0,0,323.00,"11,789.00","1,501.89","1,450.00",820.37,325.27,358.35,689.70,"1,144.00","1,450.00","1,728.25","2,332.00","2,639.65","3,790.92"
3,tt_cost,1531,3,0.20,0,0,25.91,"3,925.74",504.38,462.87,336.87,108.23,119.76,169.16,289.29,462.87,621.14,826.45,"1,005.34","1,788.55"

Distribution Summary for Saved users:

,field,row_count,null_count,null_pct,zero_count,negative_count,min,max,mean,median,std,p01,p05,p10,p25,p50,p75,p90,p95,p99
0,frequency,589,2,0.34,28,0,0.00,91.00,56.41,67.00,32.41,0.00,1.00,5.60,26.00,67.00,88.00,91.00,91.00,91.00
1,breadth,589,2,0.34,64,0,0.00,18.00,5.69,5.00,4.06,0.00,0.00,0.00,2.00,5.00,9.00,11.00,13.00,16.00
2,tenure,589,2,0.34,0,0,323.00,"10,500.00","1,542.57","1,454.00",832.41,324.86,346.00,724.00,"1,148.00","1,454.00","1,777.50","2,416.40","2,704.80","3,722.36"
3,tt_cost,589,2,0.34,0,0,36.46,"3,496.50",468.53,428.24,309.50,107.85,114.09,163.43,268.02,428.24,572.52,788.32,949.16,"1,680.29"

Distribution Summary for Stopped users:

,field,row_count,null_count,null_pct,zero_count,negative_count,min,max,mean,median,std,p01,p05,p10,p25,p50,p75,p90,p95,p99
0,frequency,942,1,0.11,155,0,0.00,91.00,39.35,33.00,34.21,0.00,0.00,0.00,4.00,33.00,76.00,89.00,91.00,91.00
1,breadth,942,1,0.11,228,0,0.00,20.00,4.64,4.00,4.22,0.00,0.00,0.00,1.00,4.00,8.00,11.00,13.00,15.00
2,tenure,942,1,0.11,0,0,324.00,"11,789.00","1,476.51","1,421.00",812.18,329.80,390.00,510.00,"1,142.00","1,421.00","1,696.00","2,245.00","2,588.00","3,752.00"
3,tt_cost,942,1,0.11,0,0,25.91,"3,925.74",526.75,483.85,351.18,109.82,154.86,169.50,311.02,483.85,645.02,839.16,"1,050.46","1,824.59"

In [8]:
for segment in SEGMENT_FIELDS:
    for name, df_i in dfs.items():
        print(f"\nSegment summary by {segment} for {name} users:")
        segment_summary = build_segment_summary(df_i, segment, NUMERIC_FIELDS)
        display(segment_summary)

Segment summary by src_risk_tier for No Action users:

,src_risk_tier,users,avg_frequency,median_frequency,p90_frequency,avg_breadth,median_breadth,p90_breadth,avg_tenure,median_tenure,p90_tenure,avg_tt_cost,median_tt_cost,p90_tt_cost
0,1. Low risk,1901,71.93,84.00,91.00,6.70,7.00,12.00,"1,565.33","1,502.00","2,393.00",621.90,523.48,"1,151.23"
2,3. Medium risk,1267,10.08,3.00,33.00,1.70,0.00,6.00,"1,278.57","1,305.00","1,670.40",597.58,568.24,888.22
1,2. Med-Low risk,1065,40.28,41.00,71.60,5.03,5.00,10.00,"1,469.87","1,425.00","2,420.80",693.48,607.12,"1,282.92"
3,4. Med-High risk,375,6.44,3.00,18.00,1.41,0.00,4.60,879.26,840.00,"1,090.00",394.05,388.48,534.33
4,5. High risk,32,12.84,1.00,81.70,2.69,1.00,9.80,808.41,724.50,"1,335.50",266.31,206.63,613.99

Segment summary by src_risk_tier for Action users:

,src_risk_tier,users,avg_frequency,median_frequency,p90_frequency,avg_breadth,median_breadth,p90_breadth,avg_tenure,median_tenure,p90_tenure,avg_tt_cost,median_tt_cost,p90_tt_cost
0,1. Low risk,560,69.38,82.00,91.00,6.74,7.00,12.00,"1,632.72","1,555.50","2,404.20",508.92,433.07,848.12
1,2. Med-Low risk,199,38.49,38.00,71.00,4.97,4.00,10.00,"1,787.80","1,725.00","2,515.20",669.61,624.04,"1,111.61"
2,3. Medium risk,170,12.21,6.00,36.20,2.11,1.00,7.00,"1,300.71","1,388.00","1,663.00",500.34,484.44,800.63
3,4. Med-High risk,74,10.16,4.50,27.10,2.23,1.00,6.00,"1,027.09",966.00,"1,481.70",336.22,303.86,500.42
4,5. High risk,1,1.00,1.00,1.00,1.00,1.00,1.00,"1,241.00","1,241.00","1,241.00",413.25,413.25,413.25

Segment summary by src_risk_tier for Saved users:

,src_risk_tier,users,avg_frequency,median_frequency,p90_frequency,avg_breadth,median_breadth,p90_breadth,avg_tenure,median_tenure,p90_tenure,avg_tt_cost,median_tt_cost,p90_tt_cost
0,1. Low risk,245,72.11,85.00,91.00,6.70,7.00,12.00,"1,644.74","1,556.00","2,524.40",469.42,392.94,846.35
1,2. Med-Low risk,69,43.70,44.00,71.20,4.93,4.00,9.00,"1,701.74","1,482.00","2,501.20",603.66,502.83,839.16
2,3. Medium risk,46,16.26,12.50,44.00,2.78,2.00,7.00,"1,261.20","1,376.00","1,658.50",445.02,474.19,616.44
3,4. Med-High risk,25,12.40,12.00,31.20,2.36,2.00,6.00,"1,017.40",968.00,"1,481.60",284.31,246.51,450.31

Segment summary by src_risk_tier for Stopped users:

,src_risk_tier,users,avg_frequency,median_frequency,p90_frequency,avg_breadth,median_breadth,p90_breadth,avg_tenure,median_tenure,p90_tenure,avg_tt_cost,median_tt_cost,p90_tt_cost
0,1. Low risk,315,67.25,80.00,91.00,6.78,7.00,12.00,"1,623.37","1,544.00","2,371.60",539.64,474.19,847.33
1,2. Med-Low risk,130,35.72,36.00,69.20,4.99,4.00,10.00,"1,833.48","1,759.00","2,514.60",704.62,645.35,"1,122.14"
2,3. Medium risk,124,10.70,3.50,33.70,1.85,0.50,6.00,"1,315.36","1,388.00","1,663.00",520.86,502.33,803.89
3,4. Med-High risk,49,9.02,3.00,24.20,2.16,1.00,7.00,"1,032.04",962.00,"1,483.80",362.70,353.31,514.87
4,5. High risk,1,1.00,1.00,1.00,1.00,1.00,1.00,"1,241.00","1,241.00","1,241.00",413.25,413.25,413.25

Segment summary by cohort for No Action users:

,cohort,users,avg_frequency,median_frequency,p90_frequency,avg_breadth,median_breadth,p90_breadth,avg_tenure,median_tenure,p90_tenure,avg_tt_cost,median_tt_cost,p90_tt_cost
0,Three-Offer Cohort,4640,42.08,37.00,90.00,4.50,4.00,10.00,"1,404.45","1,331.50","2,205.20",610.82,533.13,"1,044.88"
1,Two-Offer Cohort,3227,33.26,18.00,89.00,3.73,2.00,10.00,"1,351.97","1,362.00","1,820.00",514.24,474.19,816.96

Segment summary by cohort for Action users:

,cohort,users,avg_frequency,median_frequency,p90_frequency,avg_breadth,median_breadth,p90_breadth,avg_tenure,median_tenure,p90_tenure,avg_tt_cost,median_tt_cost,p90_tt_cost
0,Three-Offer Cohort,1004,49.14,52.00,91.00,5.27,5.00,11.00,"1,562.21","1,465.00","2,368.80",526.49,482.43,846.91
1,Two-Offer Cohort,527,39.70,32.50,88.00,4.61,4.00,10.00,"1,386.30","1,384.50","2,145.40",462.02,442.06,777.57

Segment summary by cohort for Saved users:

,cohort,users,avg_frequency,median_frequency,p90_frequency,avg_breadth,median_breadth,p90_breadth,avg_tenure,median_tenure,p90_tenure,avg_tt_cost,median_tt_cost,p90_tt_cost
0,Three-Offer Cohort,385,56.47,68.00,91.00,5.63,5.00,11.00,"1,568.39","1,454.00","2,454.20",478.55,430.97,817.25
1,Two-Offer Cohort,204,56.29,64.00,91.00,5.80,5.50,10.00,"1,493.35","1,477.50","2,237.80",449.43,422.41,724.18

Segment summary by cohort for Stopped users:

,cohort,users,avg_frequency,median_frequency,p90_frequency,avg_breadth,median_breadth,p90_breadth,avg_tenure,median_tenure,p90_tenure,avg_tt_cost,median_tt_cost,p90_tt_cost
0,Three-Offer Cohort,619,44.59,43.00,90.00,5.04,4.00,11.00,"1,558.37","1,480.00","2,332.40",556.32,502.50,862.12
1,Two-Offer Cohort,323,29.29,15.00,83.90,3.86,3.00,10.00,"1,319.15","1,328.00","1,962.10",469.92,443.22,785.93

Segment summary by Treatment for No Action users:

,Treatment,users,avg_frequency,median_frequency,p90_frequency,avg_breadth,median_breadth,p90_breadth,avg_tenure,median_tenure,p90_tenure,avg_tt_cost,median_tt_cost,p90_tt_cost
0,Control,3168,36.93,25.00,90.00,4.02,3.00,10.00,"1,382.11","1,358.00","2,060.60",566.18,502.83,908.61
1,Midpoint,3146,37.81,28.00,90.00,4.20,3.00,10.00,"1,372.44","1,359.00","2,057.00",557.85,501.50,895.50
2,Tiered,1553,42.90,40.00,90.00,4.48,4.00,10.00,"1,405.93","1,332.00","2,204.20",608.68,527.15,"1,051.92"

Segment summary by Treatment for Action users:

,Treatment,users,avg_frequency,median_frequency,p90_frequency,avg_breadth,median_breadth,p90_breadth,avg_tenure,median_tenure,p90_tenure,avg_tt_cost,median_tt_cost,p90_tt_cost
1,Midpoint,617,45.70,45.00,90.00,5.14,5.00,11.00,"1,460.30","1,421.50","2,239.00",492.77,463.87,797.53
0,Control,593,43.71,42.00,90.00,4.70,4.00,11.00,"1,493.76","1,450.00","2,300.40",489.78,446.43,804.24
2,Tiered,321,50.34,54.00,91.00,5.49,5.00,12.00,"1,596.45","1,481.00","2,460.00",553.57,484.18,905.55

Segment summary by Treatment for Saved users:

,Treatment,users,avg_frequency,median_frequency,p90_frequency,avg_breadth,median_breadth,p90_breadth,avg_tenure,median_tenure,p90_tenure,avg_tt_cost,median_tt_cost,p90_tt_cost
0,Control,344,54.79,61.00,91.00,5.58,5.00,11.00,"1,583.55","1,482.00","2,353.60",472.18,432.52,775.44
1,Midpoint,179,61.38,77.00,91.00,6.21,6.00,11.00,"1,455.69","1,424.00","2,536.20",448.76,394.17,772.41
2,Tiered,66,51.52,57.00,91.00,4.85,4.00,11.50,"1,561.95","1,453.50","2,475.00",502.51,462.87,863.30

Segment summary by Treatment for Stopped users:

,Treatment,users,avg_frequency,median_frequency,p90_frequency,avg_breadth,median_breadth,p90_breadth,avg_tenure,median_tenure,p90_tenure,avg_tt_cost,median_tt_cost,p90_tt_cost
1,Midpoint,438,39.35,32.00,87.40,4.70,4.00,10.40,"1,462.17","1,421.00","2,201.80",510.60,483.18,798.20
2,Tiered,255,50.04,54.00,91.00,5.65,5.00,12.00,"1,605.38","1,482.00","2,460.00",566.78,493.51,914.03
0,Control,249,28.40,15.00,78.00,3.49,2.00,9.00,"1,369.71","1,332.00","2,094.80",514.10,465.07,847.21

Segment summary by contact_channel for No Action users:

,contact_channel,users,avg_frequency,median_frequency,p90_frequency,avg_breadth,median_breadth,p90_breadth,avg_tenure,median_tenure,p90_tenure,avg_tt_cost,median_tt_cost,p90_tt_cost
0,No Action yet,7867,38.46,29.00,90.00,4.18,3.00,10.00,"1,382.95","1,354.00","2,069.00",571.25,502.83,949.38

Segment summary by contact_channel for Action users:

,contact_channel,users,avg_frequency,median_frequency,p90_frequency,avg_breadth,median_breadth,p90_breadth,avg_tenure,median_tenure,p90_tenure,avg_tt_cost,median_tt_cost,p90_tt_cost
0,Called-In Cancel Flow,957,49.40,54.00,91.00,5.04,5.00,10.00,"1,522.89","1,453.00","2,393.00",500.78,457.04,817.96
2,Online Cancel Flow,554,39.79,35.00,88.00,5.01,4.00,12.00,"1,449.79","1,421.00","2,166.90",508.74,474.03,826.03
3,Online first,19,49.16,50.00,89.20,5.79,6.00,10.20,"1,995.00","1,454.00","2,569.40",567.96,567.24,926.30
1,Called-In first,1,34.00,34.00,34.00,9.00,9.00,9.00,962.00,962.00,962.00,320.35,320.35,320.35

Segment summary by contact_channel for Saved users:

,contact_channel,users,avg_frequency,median_frequency,p90_frequency,avg_breadth,median_breadth,p90_breadth,avg_tenure,median_tenure,p90_tenure,avg_tt_cost,median_tt_cost,p90_tt_cost
0,Called-In Cancel Flow,486,57.47,69.00,91.00,5.59,5.00,11.00,"1,537.42","1,462.00","2,480.10",469.95,432.57,789.37
1,Online Cancel Flow,96,50.99,51.50,89.50,6.21,6.00,12.50,"1,488.64","1,454.00","2,077.00",448.54,414.70,694.82
2,Online first,7,57.29,75.00,89.40,5.57,4.00,9.80,"2,638.00","1,601.00","5,274.40",643.95,573.18,"1,176.33"

Segment summary by contact_channel for Stopped users:

,contact_channel,users,avg_frequency,median_frequency,p90_frequency,avg_breadth,median_breadth,p90_breadth,avg_tenure,median_tenure,p90_tenure,avg_tt_cost,median_tt_cost,p90_tt_cost
0,Called-In Cancel Flow,471,41.10,35.00,89.00,4.47,4.00,10.00,"1,507.92","1,423.00","2,361.90",532.53,473.53,842.14
2,Online Cancel Flow,458,37.44,29.00,88.00,4.76,4.00,12.00,"1,441.64","1,419.00","2,176.70",521.36,487.85,833.76
3,Online first,12,44.42,43.50,78.90,5.92,6.50,9.90,"1,619.92","1,452.00","2,065.90",523.62,555.85,721.45
1,Called-In first,1,34.00,34.00,34.00,9.00,9.00,9.00,962.00,962.00,962.00,320.35,320.35,320.35

Segment summary by status for No Action users:

,status,users,avg_frequency,median_frequency,p90_frequency,avg_breadth,median_breadth,p90_breadth,avg_tenure,median_tenure,p90_tenure,avg_tt_cost,median_tt_cost,p90_tt_cost
0,No Action yet,7867,38.46,29.00,90.00,4.18,3.00,10.00,"1,382.95","1,354.00","2,069.00",571.25,502.83,949.38

Segment summary by status for Action users:

,status,users,avg_frequency,median_frequency,p90_frequency,avg_breadth,median_breadth,p90_breadth,avg_tenure,median_tenure,p90_tenure,avg_tt_cost,median_tt_cost,p90_tt_cost
1,stoped,942,39.35,33.00,89.00,4.64,4.00,11.00,"1,476.51","1,421.00","2,245.00",526.75,483.85,839.16
0,saved,589,56.41,67.00,91.00,5.69,5.00,11.00,"1,542.57","1,454.00","2,416.40",468.53,428.24,788.32

Segment summary by status for Saved users:

,status,users,avg_frequency,median_frequency,p90_frequency,avg_breadth,median_breadth,p90_breadth,avg_tenure,median_tenure,p90_tenure,avg_tt_cost,median_tt_cost,p90_tt_cost
0,saved,589,56.41,67.00,91.00,5.69,5.00,11.00,"1,542.57","1,454.00","2,416.40",468.53,428.24,788.32

Segment summary by status for Stopped users:

,status,users,avg_frequency,median_frequency,p90_frequency,avg_breadth,median_breadth,p90_breadth,avg_tenure,median_tenure,p90_tenure,avg_tt_cost,median_tt_cost,p90_tt_cost
0,stoped,942,39.35,33.00,89.00,4.64,4.00,11.00,"1,476.51","1,421.00","2,245.00",526.75,483.85,839.16

Segment summary by contact_timing for No Action users:

,contact_timing,users,avg_frequency,median_frequency,p90_frequency,avg_breadth,median_breadth,p90_breadth,avg_tenure,median_tenure,p90_tenure,avg_tt_cost,median_tt_cost,p90_tt_cost
0,Contact On/After Pricing,7867,38.46,29.00,90.00,4.18,3.00,10.00,"1,382.95","1,354.00","2,069.00",571.25,502.83,949.38

Segment summary by contact_timing for Action users:

,contact_timing,users,avg_frequency,median_frequency,p90_frequency,avg_breadth,median_breadth,p90_breadth,avg_tenure,median_tenure,p90_tenure,avg_tt_cost,median_tt_cost,p90_tt_cost
0,Contact Before Pricing,989,45.86,46.00,90.00,5.12,5.00,11.00,"1,526.59","1,451.00","2,334.60",512.66,463.54,847.28
1,Contact On/After Pricing,542,45.98,45.00,90.00,4.89,4.00,11.00,"1,456.69","1,425.50","2,266.70",489.24,462.20,792.28

Segment summary by contact_timing for Saved users:

,contact_timing,users,avg_frequency,median_frequency,p90_frequency,avg_breadth,median_breadth,p90_breadth,avg_tenure,median_tenure,p90_tenure,avg_tt_cost,median_tt_cost,p90_tt_cost
0,Contact Before Pricing,347,55.85,63.50,91.00,5.67,5.00,11.00,"1,586.41","1,454.00","2,425.50",471.16,417.78,805.39
1,Contact On/After Pricing,242,57.21,69.00,91.00,5.71,5.00,11.00,"1,479.63","1,480.00","2,394.00",464.75,443.89,760.99

Segment summary by contact_timing for Stopped users:

,contact_timing,users,avg_frequency,median_frequency,p90_frequency,avg_breadth,median_breadth,p90_breadth,avg_tenure,median_tenure,p90_tenure,avg_tt_cost,median_tt_cost,p90_tt_cost
0,Contact Before Pricing,642,40.48,36.00,89.00,4.82,4.00,11.00,"1,494.35","1,423.50","2,305.50",535.03,492.84,849.98
1,Contact On/After Pricing,300,36.92,27.00,89.00,4.23,4.00,10.00,"1,438.20","1,419.00","2,211.40",508.98,472.53,798.40

Segment summary by repeatedly_called for No Action users:

,repeatedly_called,users,avg_frequency,median_frequency,p90_frequency,avg_breadth,median_breadth,p90_breadth,avg_tenure,median_tenure,p90_tenure,avg_tt_cost,median_tt_cost,p90_tt_cost
0,0,7867,38.46,29.00,90.00,4.18,3.00,10.00,"1,382.95","1,354.00","2,069.00",571.25,502.83,949.38

Segment summary by repeatedly_called for Action users:

,repeatedly_called,users,avg_frequency,median_frequency,p90_frequency,avg_breadth,median_breadth,p90_breadth,avg_tenure,median_tenure,p90_tenure,avg_tt_cost,median_tt_cost,p90_tt_cost
0,0,1518,45.69,45.00,90.00,5.03,4.00,11.00,"1,500.95","1,450.00","2,328.00",505.15,463.20,826.59
1,1,13,73.00,89.00,91.00,6.00,5.00,9.90,"1,619.92","1,432.00","2,777.30",407.48,418.10,701.71

Segment summary by repeatedly_called for Saved users:

,repeatedly_called,users,avg_frequency,median_frequency,p90_frequency,avg_breadth,median_breadth,p90_breadth,avg_tenure,median_tenure,p90_tenure,avg_tt_cost,median_tt_cost,p90_tt_cost
0,0,576,56.06,66.00,91.00,5.68,5.00,11.00,"1,540.95","1,454.00","2,394.00",469.80,430.82,788.54
1,1,13,73.00,89.00,91.00,6.00,5.00,9.90,"1,619.92","1,432.00","2,777.30",407.48,418.10,701.71

Segment summary by repeatedly_called for Stopped users:

,repeatedly_called,users,avg_frequency,median_frequency,p90_frequency,avg_breadth,median_breadth,p90_breadth,avg_tenure,median_tenure,p90_tenure,avg_tt_cost,median_tt_cost,p90_tt_cost
0,0,942,39.35,33.00,89.00,4.64,4.00,11.00,"1,476.51","1,421.00","2,245.00",526.75,483.85,839.16

# stoped vs saved - Histogram

In [10]:
for col in NUMERIC_FIELDS:
    for name, df_i in islice(reversed(dfs.items()), 2):
        plot_histogram_with_log(
            data=df_i,
            metric=col,
            group=name,
            chart_folder=str(CHART_DIR / "histograms" / name),
        )

# stoped vs saved - Correlation, Pairplot, Scatterplot

In [11]:
for name, df_i in islice(reversed(dfs.items()), 2):
    plot_correlation_heatmap(
        df_i,
        NUMERIC_FIELDS,
        name,
        chart_folder=str(CHART_DIR / "correlations"),
    )

In [12]:
# sample_df = df[NUMERIC_FIELDS].dropna().sample(
#     min(5000, len(df.dropna())),
#     random_state=42
# )

# sns.pairplot(sample_df)
# plt.show()

In [13]:
pairs = [
    ("frequency", "breadth"),
    ("frequency", "tenure"),
    ("frequency", "tt_cost"),
    ("breadth", "tenure"),
    ("breadth", "tt_cost"),
    ("tenure", "tt_cost")
]

for name, df_i in islice(reversed(dfs.items()), 2):
    plot_scatter_pairs(
        df_i,
        pairs,
        chart_folder=str(CHART_DIR / "scatter" / name),
        file_name="{pair}.png",
    )

# stoped vs saved - Custom bucket

In [14]:
for name, df_i in islice(reversed(dfs.items()), 2):
    df_i["tenure_bucket"] = pd.cut(
        df_i["tenure"],
        bins=[-np.inf, 0, 30, 90, 180, 365, 730, np.inf],
        labels=[
            "0 or less",
            "1-30 days",
            "31-90 days",
            "91-180 days",
            "181-365 days",
            "1-2 years",
            "2+ years"
        ]
    )
    bucket_cols = ["tenure_bucket"] #, "cost_bucket", "frequency_bucket"]
    for col in bucket_cols:
        bucket_counts = plot_bucket_counts(
            df_i,
            col,
            chart_folder=str(CHART_DIR / "bucket_counts"),
            file_name=f"{col}_counts_{name}_users.png"
        )
        display(bucket_counts)

  tenure_bucket  count
0      2+ years    822
1     1-2 years     78
2  181-365 days     41
3           NaN      1
4     0 or less      0
5     1-30 days      0
6    31-90 days      0
7   91-180 days      0

  tenure_bucket  count
0      2+ years    526
1  181-365 days     37
2     1-2 years     24
3           NaN      2
4     0 or less      0
5     1-30 days      0
6    31-90 days      0
7   91-180 days      0

# Business Boxplots

In [18]:
# No Action vs Had Action
df["action_group"] = np.where(
    df["status"].eq("No Action yet"),
    "No Action yet",
    "Had Action"
)
_ = plot_full_and_clipped_boxplot(
    data=df,
    metrics=NUMERIC_FIELDS,
    group_col="action_group",
    group_order=["No Action yet", "Had Action"],
    chart_title="Metrics: No Action vs Had Action",
    figsize=(10, 5),
    chart_folder=str(CHART_DIR / "boxplots"),
    file_name="metrics_no_action_vs_had_action.png",
)

In [19]:
# Stoped vs Saved
# Repeated called vs Not
df_action["repeated_call_group"] = np.where(
    df_action["repeatedly_called"].fillna(0).astype(int).eq(1),
    "Repeatedly Called",
    "Called Once"
)
group_kwargs = {
    "group_col": ["status", "repeated_call_group"],
    "group_order": [["saved", "stoped"], ["Repeatedly Called", "Called Once"]]
}

for col, order in zip(group_kwargs["group_col"], group_kwargs["group_order"]):
    _ = plot_full_and_clipped_boxplot(
        data=df_action,
        metrics=NUMERIC_FIELDS,
        group_col=col,
        group_order=order,
        chart_title=f"Metrics: {order[0]} vs {order[1]}",
        figsize=(10, 5),
        chart_folder=str(CHART_DIR / "boxplots"),
        file_name=f"metrics_{order[0]}_vs_{order[1]}.png",
    )

In [14]:
# Stoped vs Saved outliers
for name, df_i in islice(reversed(dfs.items()), 2):
    outlier_df = build_outlier_summary(df_i, NUMERIC_FIELDS)
    print(f"Outlier Summary for {name} users:")
    display(outlier_df)

Outlier Summary for Stopped users:

,field,q1,q3,iqr,lower_bound,upper_bound,outlier_count,outlier_pct
0,frequency,4.00,76.00,72.00,-104.00,184.00,0,0.00
1,breadth,1.00,8.00,7.00,-9.50,18.50,1,0.11
2,tenure,"1,142.00","1,696.00",554.00,311.00,"2,527.00",53,5.63
3,tt_cost,311.02,645.02,334.00,-189.98,"1,146.02",39,4.14

Outlier Summary for Saved users:

,field,q1,q3,iqr,lower_bound,upper_bound,outlier_count,outlier_pct
0,frequency,26.00,88.00,62.00,-67.00,181.00,0,0.00
1,breadth,2.00,9.00,7.00,-8.50,19.50,0,0.00
2,tenure,"1,148.00","1,777.50",629.50,203.75,"2,721.75",28,4.75
3,tt_cost,268.02,572.52,304.50,-188.72,"1,029.27",21,3.57

In [21]:
# Slices of Segments boxplots
slice_fields=["contact_channels", "cohort", "src_risk_tier", "contact_timing"]
res = plot_slices_of_segments_boxplot(
    df_action,
    metrics=NUMERIC_FIELDS,
    slice_fields=slice_fields,
    chart_folder=str(CHART_DIR / "boxplots"),
    full_file_name="segment_slices_full.png",
    clipped_file_name="segment_slices_clipped.png",
    standardized_clipped_file_name="segment_slices_standardized_clipped.png",
    slices_per_file=6,
    n_cols=2
)

,contact_channels,cohort,src_risk_tier,contact_timing,Treatment,users
0,Called-In Cancel Flow,Three-Offer Cohort,1. Low risk,Contact Before Pricing,Control,87
1,Called-In Cancel Flow,Three-Offer Cohort,1. Low risk,Contact Before Pricing,Midpoint,84
2,Called-In Cancel Flow,Three-Offer Cohort,1. Low risk,Contact Before Pricing,Tiered,75
3,Called-In Cancel Flow,Three-Offer Cohort,1. Low risk,Contact On/After Pricing,Control,41
4,Called-In Cancel Flow,Three-Offer Cohort,1. Low risk,Contact On/After Pricing,Midpoint,50

Preparing 29 unique segment combinations...
No groups meet the minimum sample size.
No groups meet the minimum sample size.
No groups meet the minimum sample size.
No groups meet the minimum sample size.
No groups meet the minimum sample size.
No groups meet the minimum sample size.
No groups meet the minimum sample size.
No groups meet the minimum sample size.
No groups meet the minimum sample size.
No groups meet the minimum sample size.

# WIP

In [ ]:
# distribution_summary.to_csv("distribution_summary.csv")
# quality_df.to_csv("data_quality_summary.csv", index=False)
# outlier_df.to_csv("outlier_summary.csv", index=False)

# print("Saved summary files.")

In [ ]:
# percentile_query = f"""
# SELECT
#   COUNT(*) AS row_count,

#   APPROX_QUANTILES(tenure, 100)[OFFSET(1)] AS tenure_p01,
#   APPROX_QUANTILES(tenure, 100)[OFFSET(25)] AS tenure_p25,
#   APPROX_QUANTILES(tenure, 100)[OFFSET(50)] AS tenure_p50,
#   APPROX_QUANTILES(tenure, 100)[OFFSET(75)] AS tenure_p75,
#   APPROX_QUANTILES(tenure, 100)[OFFSET(90)] AS tenure_p90,
#   APPROX_QUANTILES(tenure, 100)[OFFSET(95)] AS tenure_p95,
#   APPROX_QUANTILES(tenure, 100)[OFFSET(99)] AS tenure_p99,

#   APPROX_QUANTILES(total_cost, 100)[OFFSET(1)] AS total_cost_p01,
#   APPROX_QUANTILES(total_cost, 100)[OFFSET(25)] AS total_cost_p25,
#   APPROX_QUANTILES(total_cost, 100)[OFFSET(50)] AS total_cost_p50,
#   APPROX_QUANTILES(total_cost, 100)[OFFSET(75)] AS total_cost_p75,
#   APPROX_QUANTILES(total_cost, 100)[OFFSET(90)] AS total_cost_p90,
#   APPROX_QUANTILES(total_cost, 100)[OFFSET(95)] AS total_cost_p95,
#   APPROX_QUANTILES(total_cost, 100)[OFFSET(99)] AS total_cost_p99,

#   APPROX_QUANTILES(viewed_number_of_pages, 100)[OFFSET(1)] AS pages_p01,
#   APPROX_QUANTILES(viewed_number_of_pages, 100)[OFFSET(25)] AS pages_p25,
#   APPROX_QUANTILES(viewed_number_of_pages, 100)[OFFSET(50)] AS pages_p50,
#   APPROX_QUANTILES(viewed_number_of_pages, 100)[OFFSET(75)] AS pages_p75,
#   APPROX_QUANTILES(viewed_number_of_pages, 100)[OFFSET(90)] AS pages_p90,
#   APPROX_QUANTILES(viewed_number_of_pages, 100)[OFFSET(95)] AS pages_p95,
#   APPROX_QUANTILES(viewed_number_of_pages, 100)[OFFSET(99)] AS pages_p99

# FROM `{TABLE_ID}`
# """

# percentiles_bq = client.query(percentile_query).to_dataframe()
# percentiles_bq